#@ load("@ytt:data", "data")

apiVersion: accelerator.apps.tanzu.vmware.com/v1alpha1
kind: Accelerator
metadata:
  name: python
  namespace: accelerator-system 
spec:
  git:
    url: #@ data.values.giturl
    ref:
      branch: main
