#@ load("@ytt:data", "data")
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: #@ data.values.projectName
  description: #@ data.values.description
  tags:
    - python
    - streamlit
  annotations:
    'backstage.io/kubernetes-label-selector': 'app=python-test01-00001'
spec:
  type: service
  lifecycle: experimental
  owner: default-team
